dist: bionic
language: ruby
rvm:
  - 2.6.3

cache: bundler # caching bundler gem packages will speed up build
sudo: false # route your build to the container-based infrastructure for a faster build

before_install:
  - gem update --system
  - gem install bundler
  - npm install
  # - bundle install

script: npm run build

deploy:
  provider: pages
  local-dir: ./_site
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  keep-history: true
  verbose: true
  github-token: $GITHUB_TOKEN
  target_branch: release
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
branches:
  only:
  - master