url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
# Google Analytics code
ga_code: UA-22730035-2

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - gulpfile.js