url: "https://bogdanmic.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Software recipes" # the name of your site, e.g. ACME Corp.
# Google Analytics code
ga_code: UA-22730035-2

sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass
    - node_modules

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [local]
  startings: [html, head, body]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - gulpfile.js

# Custom variables:
github_handle: bogdanmic
twitter_handle: micbogdan